/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check
import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
    workersSidebar: [
        {
            type: "doc",
            id: "workers/index"
        },
        { type: "autogenerated", dirName: "workers/email" },
        {
            type: "category",
            label: "Actions Worker",
            link: {
                type: "generated-index",
                title: "Actions Worker",
                slug: "/workers/actions"
            },
            items: require("./docs/workers/actions/sidebar.ts")
        },
        {
            type: "category",
            label: "Auth Worker",
            link: {
                type: "generated-index",
                title: "Auth Worker",
                slug: "/workers/auth"
            },
            items: require("./docs/workers/auth/sidebar.ts")
        },
        {
            type: "category",
            label: "Google Forms Worker",
            link: {
                type: "generated-index",
                title: "Google Forms Worker",
                slug: "/workers/googleforms"
            },
            items: require("./docs/workers/googleforms/sidebar.ts")
        },
        { type: "autogenerated", dirName: "workers/utils" },
        { type: "autogenerated", dirName: "workers/scheduled" }
    ],
    esnRecruitmentSidebar: [
        {
            type: "doc",
            id: "esn-recruitment/index"
        },
        {
            type: "category",
            label: "API",
            link: {
                type: "generated-index",
                title: "ESN Recruitment API",
                slug: "/esn-recruitment/api"
            },
            items: require("./docs/esn-recruitment/api/sidebar.ts")
        },
        {
            type: "category",
            label: "Modules",
            link: {
                type: "generated-index",
                title: "ESN Recruitment Modules",
                slug: "/esn-recruitment/modules"
            },
            items: require("./docs/esn-recruitment/modules/sidebar.ts")
        }
    ],
    qedSidebar: [{ type: "autogenerated", dirName: "qed" }]
    // openApiSidebar: [
    //     {
    //         type: "category",
    //         label: "Petstore",
    //         link: {
    //             type: "generated-index",
    //             title: "Petstore API",
    //             description: "This is a sample server Petstore server. You can find out more about Swagger at http://swagger.io or on irc.freenode.net, #swagger. For this sample, you can use the api key special-key to test the authorization filters.",
    //             slug: "/category/petstore-api"
    //         },
    //         items: require("./docs/petstore/sidebar.ts")
    //     }
    // ]
};

export default sidebars;
