/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check
import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
    workersSidebar: [
        {
            type: "doc",
            id: "workers/index"
        },
        {
            type: "category",
            label: "Email Worker",
            link: {
                type: "generated-index",
                title: "Email Worker",
                slug: "/workers/email"
            },
            items: require("./docs/workers/email/sidebar.ts")
        },
        {
            type: "category",
            label: "Actions Worker",
            link: {
                type: "generated-index",
                title: "Actions Worker",
                slug: "/workers/actions"
            },
            items: require("./docs/workers/actions/sidebar.ts")
        },
        {
            type: "category",
            label: "Auth Worker",
            link: {
                type: "generated-index",
                title: "Auth Worker",
                slug: "/workers/auth"
            },
            items: require("./docs/workers/auth/sidebar.ts")
        },
        {
            type: "category",
            label: "Google Forms Worker",
            link: {
                type: "generated-index",
                title: "Google Forms Worker",
                slug: "/workers/googleforms"
            },
            items: require("./docs/workers/googleforms/sidebar.ts")
        },
        {
            type: "category",
            label: "Utils Worker",
            link: {
                type: "generated-index",
                title: "Utils Worker",
                slug: "/workers/utils"
            },
            items: require("./docs/workers/utils/sidebar.ts")
        },
        {
            type: "category",
            label: "Scheduled Worker",
            link: {
                type: "generated-index",
                title: "Scheduled Worker",
                slug: "/workers/scheduled"
            },
            items: require("./docs/workers/scheduled/sidebar.ts")
        }
    ],
    esnRecruitmentSidebar: [
        {
            type: "doc",
            id: "esn-recruitment/index"
        },
        {
            type: "category",
            label: "API",
            link: {
                type: "generated-index",
                title: "ESN Recruitment API",
                slug: "/esn-recruitment/api"
            },
            items: require("./docs/esn-recruitment/api/sidebar.ts")
        },
        {
            type: "category",
            label: "Modules",
            link: {
                type: "generated-index",
                title: "ESN Recruitment Modules",
                slug: "/esn-recruitment/modules"
            },
            items: require("./docs/esn-recruitment/modules/sidebar.ts")
        }
    ],
    qedSidebar: [{ type: "autogenerated", dirName: "qed" }]
};

export default sidebars;
